/diffdrive_kin_sim:

    # integration step
    dt: 0.001

    # robot initial state
    x0: 0.0                     # position x
    y0: 0.0                     # position y
    theta0: 0.0                 # heading

    # distance between the two wheels
    d: 0.15

    # radius of the two wheels
    r: 0.03

