# simulator configuration parameters
/diffdrive_kin_sim/dt: 0.001                   # integration step

# vehicle initial state
/diffdrive_kin_sim/x0: 0.0                     # initial position x
/diffdrive_kin_sim/y0: 0.0                     # initial position y
/diffdrive_kin_sim/theta0: 0.0                 # initial heading

/diffdrive_kin_sim/d: 0.15                # distance between the two wheels
/diffdrive_kin_sim/r: 0.03                # radius of the two wheels

