my_dwa_planner:

  min_vel_y: 0.0
  max_vel_y: 0.0

  min_vel_x: 0.0
  max_vel_x: 10.0
  
  acc_lim_theta: 10.0

  # DEPRECATED! (to be written in the report: doc is outdated...)
  #min_rot_vel: 0.0
  #max_rot_vel: 0.0

  # CORRECTLY WORKING!
  #min_vel_theta: 0.0
  #max_vel_theta: 0.0

  vth_samples: 100 #default 20
  vx_samples: 30 #default 3

  #sim_time: 6.0
  #sim_granularity: 0.01
  forward_point_distance: 0.05
  
  ### Cost function weights
  path_distance_bias: 50.0
  goal_distance_bias: 100.0
  #occdist_scale: 0.01
  ###
  
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 6.3
