# blank image with no obstacles
image: maps/map.png
resolution: 0.1

# make the 10x10 image centered in the origin
origin: [-5.0, -5.0, 0.0]

# other default parameters required to run map server
occupied_thresh: 0.65
free_thresh: 0.196
negate: 0

