#
# source: https://answers.ros.org/question/336933/how-to-load-a-mappng-to-ros-and-make-an-occupancy-grid/]
#

image: maps/map.png
resolution: 0.1
origin: [-5.0, -5.0, 0.0]
occupied_thresh: 0.65
free_thresh: 0.196
negate: 0

