# Controller configuration parameters
  /bicycle_kin_trajctrl/run_period: 0.01          # Node execution period

# Controller parameters
  /bicycle_kin_trajctrl/P_dist: 0.12              # Distance of point P from odometric center
  /bicycle_kin_trajctrl/l: 0.26                   # Bicycle length
  /bicycle_kin_trajctrl/Kx: 1.0                   # PD trajectory tracking controller gain for x direction
  /bicycle_kin_trajctrl/Ky: 1.0                   # PD trajectory tracking controller gain for y direction

